name: Test-Build

on:
  push:
    branches: 
     - master

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          

      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults
      
      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run petstore.collection.json -r htmlextra -x --reporter-htmlextra-export testResults/index.html
        
 
      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.POSTMANACTIONS }}
          publish_dir: ./testResults
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          
      
          
